#!/bin/bash

echo "==================================="
echo "Namecheap API Setup for finally.gold"
echo "==================================="
echo ""
echo "CURRENT DNS STATUS:"
echo "-------------------"
echo "finally.gold currently points to: $(dig finally.gold +short)"
echo "www.finally.gold currently points to: $(dig www.finally.gold +short)"
echo ""
echo "This domain is currently using Namecheap's parking page."
echo "We need to configure it to point to GitHub Pages."
echo ""
echo "==================================="
echo "STEP 1: Get Namecheap API Access"
echo "==================================="
echo ""
echo "1. Log in to Namecheap: https://www.namecheap.com"
echo ""
echo "2. Go to Profile -> Tools -> API Access"
echo "   Direct link: https://ap.www.namecheap.com/settings/tools/apiaccess"
echo ""
echo "3. Enable API Access if not already enabled"
echo ""
echo "4. Whitelist your IP address:"
echo "   Your current IP is: $(curl -s https://api.ipify.org)"
echo "   Add this IP to the whitelist"
echo ""
echo "5. Copy your API credentials:"
echo "   - API Key: (long string)"
echo "   - Username: (your Namecheap username)"
echo ""
echo "==================================="
echo "STEP 2: Add Credentials to Doppler"
echo "==================================="
echo ""
echo "Run these commands to add credentials to Doppler:"
echo ""
echo "doppler secrets set NAMECHEAP_API_KEY"
echo "# Paste your API key when prompted"
echo ""
echo "doppler secrets set NAMECHEAP_API_USER"
echo "# Enter your Namecheap username when prompted"
echo ""
echo "doppler secrets set NAMECHEAP_USERNAME"  
echo "# Enter your Namecheap username again (usually same as API_USER)"
echo ""
echo "==================================="
echo "STEP 3: Run DNS Configuration"
echo "==================================="
echo ""
echo "After adding credentials to Doppler, run:"
echo ""
echo "doppler run -- python /Users/lech/scheduler/configure_namecheap_dns.py"
echo ""
echo "This will automatically configure:"
echo "  - 4 A records for finally.gold → GitHub Pages IPs"
echo "  - 1 CNAME record for www.finally.gold → leolech14.github.io"
echo "  - All with 1-minute TTL for fast propagation"
echo ""
echo "==================================="
echo "ALTERNATIVE: Manual Configuration"
echo "==================================="
echo ""
echo "If you prefer to configure manually, follow the instructions in:"
echo "/Users/lech/scheduler/ai-events-2025/namecheap_dns_instructions.md"
echo ""
echo "==================================="